apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{ .Chart.Name }}-nginx"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
{{ toYaml .Values.selectorLabels | indent 6 }}      
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
{{ toYaml .Values.selectorLabels | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository.nginx }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.containerPort | int }}

        resources:
{{ toYaml .Values.resources | indent 10 }}